export const taglines = [
         "Please Login to see secure data and manage your account.",
         "Please Login to see secure and complete details of my trades on our website at https://bitcointalk.org/.",
         "Please Login to see secure SSL certificates on your website.",
         "Please Login to see secure access after 15 days.",
         "Please Login to see secure plans.",
         "Please Login to see secure versions of your passwords and data",
         "Please Login to see secure links from our community.",
         "Please Login to see secure ecommerce payments for orders over US$10.",
         "Please Login to see secure emails. Password Confirmation The passwords you entered don't match. Create Account",
         "Please Login to see secure domains (we don't do the registration)",
         "Please Login to see secure passwords for all users",
         "Please Login to see secure, local email addresses of your customer's customers without having to log in",
         "Please Login to see secure transfers.",
         "Please Login to see secure links to your new account",
         "Please Login to see secure password reset.",
         "Please Login to see secure passwords for all your sites and allow me to know which browsers you can use for your account.",
         "Please Login to see secure links / Sign-up for all newsletters",
         "Please Login to see secure versions of your site and login anytime!",
         "Please Login to see secure messages from this site immediately. Enter Your email, Password, or Paypal Password to sign-up",
         "Please Login to see secure files or access your files remotely. We guarantee that you will receive an email alert when a new lease is signed.",
         "Please Login to see secure password updates",
         "Please Login to see secure browsing. Register now",
         "Please Login to see secure data for all your websites.",
         "Please Login to see secure connection statistics for each domain.",
         "Please Login to see secure content.",
         "Please Login to see secure connection",
         "Please Login to see secure links.",
         "Please Login to see secure access to the webpages of our authorized resellers. Your email is required.",
         "Please Login to see secure usage in Chrome. More Info",
         "Please Login to see secure access to your account.",
         "Please Login to see secure e-mail alerts You can login to gain access to all the content of our archives",
         "Please Login to see secure and easy password management of your emails and other encrypted messages without having to login again.",
         "Please Login to see secure login information. Password Is required, Please fill out this field. Password must be at least 8 characters long. Password",
         "Please Login to see secure content, not just your name and email address, as long as it's on your website",
         "Please Login to see secure passwords | Sign in Your e-mail address and password will not be shared with anyone and you may receive email from",
         "Please Login to see secure data for a limited time. Login How-To Now Learn more and learn how to log in.",
         "Please Login to see secure access to your database",
         "Please Login to see secure transfers using our ePass technology. Sign up on our site and see your purchases added to our ePass. You",
         "Please Login to see secure and authentic email addresses",
         "Please Login to see secure transfers from your account. Password Confirmation The passwords you entered don't match. Create Account",
         "Please Login to see secure e-mail, web access",
         "Please Login to see secure content",
         "Please Login to see secure connection to Cloud9.",
         "Please Login to see secure connections to your site",
         "Please Login to see secure accounts.",
         "Please Login to see secure, private messages protected with HTTPS\u2122 encryption.",
         "Please Login to see secure messages in Slack (recommended).",
         "Please Login to see secure transactions and secure files in your site.",
         "Please Login to see secure updates from our site.",
         "Please Login to see secure Plans, for use on your local network. Please see our Privacy Policy for more information. Privacy Notice For information on"
]